[phases.setup]
nixPkgs = ["ffmpeg", "nodejs_20", "chromium"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node src/server.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/nix/var/nix/profiles/default/bin/chromium"
CHROMIUM_PATH = "/nix/var/nix/profiles/default/bin/chromium"
